config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'imc_area/index'
  get 'imc_area/calculo'
  get 'imc_area/resultado'

  get 'imc_area/very_low_weight'
  get 'imc_area/low_weight'
  get 'imc_area/normal_weight'
  get 'imc_area/overweight'
  get 'imc_area/obesityI'
  get 'imc_area/obesityII'
  get 'imc_area/obesityIII'

  get '/calculo', to:'imc_area#index'
  post '/calculo', to: 'imc_area#calculo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/imc_area_controller.rb
class ImcAreaController < ApplicationController
  def index
    @height = nil
    @weight = nil

  end

  def very_low_weight

  end

  def low_weight

  end

  def normal_weight

  end

  def overweight

  end

  def obesityI
  end

  def obesityII
  end

  def obesityIII
    #
  end


  def calculo
    @height = params[:height].to_f # altura
    @weight = params[:weight].to_f # peso

    if @height && @weight > 0
      imc = @weight / ( @height ** 2 )
      imc = imc.ceil(1)

      if imc < 16.9
        redirect_to  imc_area_very_low_weight_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Você está muito abaixo do peso!"

      elsif imc > 17 && imc < 18.4
        redirect_to imc_area_low_weight_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Você está abaixo do peso!"

      elsif imc > 18.5 && imc < 24.9
        redirect_to imc_area_normal_weight_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Você está com peso normal!"

      elsif imc > 25 && imc < 29.9
        redirect_to imc_area_overweight_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Você está acima do peso!"

      elsif imc > 30 && imc < 34.9
        redirect_to imc_area_obesityI_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Obesidade grau I!"

      elsif imc > 35 && imc < 40
        redirect_to imc_area_obesityII_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Obesidade grau II!"

      elsif imc > 40
        redirect_to imc_area_obesityIII_path
        flash[:imc] = "Seu imc é de: #{imc}"
        flash[:situacao] = "Obesidade grau III!"

      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imc_area_helper.rb
module ImcAreaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/imc_area/calculo.html.erb
<div class="container-form">
  <div class='Forms'>
  <%= form_tag('/calculo') do %>
    <%= label_tag :height, 'Enter your height', class:'label-height' %><br>
    <%= text_field_tag :height, nil, class:'field-height_'%><br>
    
    <%= label_tag :weight, 'Enter your weight', class:'label-wight' %><br>
    <%= text_field_tag :weight, nil, class:'field-wight_'%><br>
    
    <%= submit_tag "Calcl", class:'btn-calc' %>
  
  <% end %>
  
  <%= link_to "Back", root_path, class:'link' %>
  </div>
</div>

app/views/imc_area/index.html.erb
<section class="imc_area_section">
  <h1 class="title_imcarea">ImcArea</h1>
  <span class="text_imc_area">
    Please enter your height and weight in numbers only, example: (1.79 <- Height) (72.5 <- Weight).
    It is not necessary to inform the Kg's or M, mm and cm of the height!
  
  </span>
  
  <%= link_to 'Form', imc_area_calculo_path, class:'go_to_calcl' %>
  
</section>

app/views/imc_area/low_weight.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "low_weight.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>

<div class='what_this'>
    <h1> What is this </h1>
        <span>
            Underweight refers to a body mass index (BMI) below 18.5, indicating a weight insufficient for a person's height.
            Inadequate food intake: Not consuming enough calories or nutrients to meet the body's needs.
            Malnutrition: Lack of essential nutrients necessary for proper bodily functions.
            Underlying medical conditions: Certain diseases or disorders, such as digestive issues, hyperthyroidism, or cancer, can lead to unintended weight loss.

        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            Increasing calorie intake: Consuming more calories than expended can help promote weight gain. This typically involves eating frequent, nutrient-dense meals and snacks.
            Nutrient-rich diet: Emphasizing foods high in protein, healthy fats, complex carbohydrates, vitamins, and minerals can support overall health and weight gain.
            Strength-building exercises: Incorporating resistance training can help build muscle mass, contributing to healthy weight gain.

        </span>
</div>

app/views/imc_area/normal_weight.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "normal_weight.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>

<div class='what_this'>
    <h1> What is this </h1>
        <span>
            People falling within the healthy weight category have a BMI between 18.5 and 24.9, suggesting a balanced weight relative to height.

        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            Maintaining a healthy lifestyle, including a balanced diet and regular exercise, is crucial for maintaining a healthy weight.

        </span>
</div>

app/views/imc_area/obesityI.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "obsetiyI.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>

</div>

<div class='what_this'>
    <h1> What is this </h1>
        <span>
             Obesity grade I is characterized by a BMI between 30 and 34.9, indicating a significant excess of weight relative to height.

        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            In addition to lifestyle changes, medically supervised interventions such as weight loss medications may be considered in cases of obesity grade I.

        </span>
</div>

app/views/imc_area/obesityII.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "obsetiyII.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>

<div class='what_this'>
    <h1> What is this </h1>
        <span>
             Obesity grade II is indicated by a BMI between 35 and 39.9, representing severe excess weight relative to height.
        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            More intensive medical interventions, such as bariatric surgery, may be recommended in cases of obesity grade II, along with significant lifestyle changes.

        </span>
</div>

app/views/imc_area/obesityIII.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "obsetiyI.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>


<div class='what_this'>
    <h1> What is this </h1>
        <span>
            Obesity grade III, also known as morbid obesity, is characterized by a 
            BMI of 40 or above, representing extreme excess weight relative to height. 
            Causes may include genetic predisposition, metabolic disorders, unhealthy 
            lifestyle choices, or certain medical conditions.
        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            Treatment for obesity grade III 
            typically requires a multidisciplinary
            approach, including medical interventions, 
            diet, exercise, and in some cases, 
            bariatric surgery to reduce the risk of 
            serious health complications.
        </span>
</div>

app/views/imc_area/overweight.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "overweight.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>

<div class='what_this'>
    <h1> What is this </h1>
        <span>
           Individuals classified as overweight have a BMI between 25 and 29.9, indicating excess weight relative to height.

        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            Weight loss strategies such as diet and regular physical activity are recommended to reduce the risk of obesity-related health issues.
            
        </span>
</div>

app/views/imc_area/resultado.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= "asdasdwedrfdwerf" %><br>
        <%= "asdasdasdas" %>
    
    </div>

    <%= image_tag "low_weight.png", size:'220x220', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>

app/views/imc_area/very_low_weight.html.erb
<div class='result'>
    <h1>Result</h1>
    <div class='alerts'>
        <%= flash[:imc]%><br>
        <%= flash[:situacao] %>
    
    </div>

    <%= image_tag "very_low_weight.png", size:'220x200', style:'margin: 15px 0 0 0;', class:'imc-icon'%>
</div>


<div class='what_this'>
    <h1> What is this </h1>
        <span>
             Individuals classified as underweight have a body mass index (BMI) below 18.5, 
             indicating insufficient weight relative to height. Causes may include inadequate food intake, 
             malnutrition, underlying medical conditions, or genetic factors.

        </span> 

      <h1 class='part2'> Treatment </h1>
        <span>
            Treatment may involve increasing calorie intake, 
            consuming a nutrient-rich balanced diet, strength-building exercises, 
            and regular medical monitoring.
            
        </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imc2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <!--Icon home-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "wave", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "welcome_index", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "imc_area", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "forms", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "result", "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class='header_app'>
      <h1 class='title_app'>Calc for IMC</h1>
      <%= link_to "home", root_path, class:"material-symbols-outlined" %>

    </header>

    <section class="container">
      <div class="wave"></div>

      <div class='conteudo'>
        <%= yield %>

      </div>

    </section>


  </body>
</html>

app/views/welcome/index.html.erb
<section class='start_section'>
  <h1 class="title_start">Gets Start</h1>
  <span class="text_gets_start">
    To get the most out of the website, we ask that you follow the requested items step by step, such as weight and height!

  </span>
</section>

<section class="go_to_imc_calc">
  <%= link_to "Go to IMC Calc", imc_area_index_path , class:"h2_title_imc"%>
  
</section>